---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: model-a
spec:
  name: model-a
  predictors:
  - graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: gs://seldon-models-dhs/mlflow/model-a
      name: wines-classifier
    name: default
    replicas: 1

